name: Test

on:
  push:
    branches-ignore:
      "prerelease-*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install proper core version
        run: |
          source .buildversions
          npm install @polygloat/core@${CORE_VERSION}

      - name: Npm install
        run: npm install

      - name: Unit test
        run: npm run test

      - name: Build
        run: npm run build